;;; json-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from json-mode.el

(add-to-list 'auto-mode-alist '("\\.json\\'" . json-mode))
(autoload 'json-mode "json-mode" "\
Major mode for editing JavaScript Object Notation (JSON) data files.

(fn)" t)
(register-definition-prefixes "json-mode" '("json-"))

;;; End of scraped data

(provide 'json-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; json-mode-autoloads.el ends here
